
#MysteryDish
#Sam Breece

#This file contains the potential mystery dishes
#pizza, pho, paella, curry, tacos, sushi, spaghetti, hamburger
dishes = [ 
    {"name":"spaghetti",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""},
    {"name":"pizza",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""}, 
    {"name":"pho",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""},
    {"name":"paella",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""},
    {"name":"curry",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""}, 
    {"name":"tacos",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""},
    {"name":"paella",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""},
    {"name":"sushi",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""}, 
    {"name":"hamburger",
     "ingredients": ["","","", ""],
     "colors": ["", "", ""],
     "temperature": "",
      "origin": ""}
    ]
