#MysteryDish
#Sam Breece

#This file contains the potential mystery dishes to be used with my week 1 project
#pizza, pho, paella, curry, tacos, sushi, spaghetti, hamburger
dishes = [ 
    {"name":"spaghetti",
     "first letter":"s",
     "ingredients": ["pasta","tomato sauce","cheese", "spaghetti noodles", "noodles"],
     "temperature": "hot",
      "origin": "Italy"},
    {"name":"pizza",
     "first letter":"p",
     "ingredients": ["flour","tomato sauce","cheese", "pepperoni", "dough", "herbs", "mushrooms", "pineapple"],
     "temperature": "hot",
      "origin": "Italy"}, 
    {"name":"pho",
     "first letter":"p",
     "ingredients": ["bone broth", "broth","rice noodles","herbs", "meat", "star anise", "cloves", "spices"],
     "temperature": "hot",
      "origin": "Vietnam"},
    {"name":"paella",
     "first letter":"p",
     "ingredients": ["rice","beans","saffron", "seafood", "rabbit", "chicken"],
     "temperature": "hot",
      "origin": "Spain"},
    {"name":"curry",
     "first letter":"c",
     "ingredients": ["garlic","curry powder","coconut cream", "tumeric", "ginger", "chilies", "cumin", "spices"],
     "temperature": "hot",
      "origin": "India"}, 
    {"name":"taco",
     "first letter":"t",
     "ingredients": ["tortilla","cilantro","onion", "carne asada", "carnitas", "al pastor", "lime"],
     "temperature": "hot",
      "origin": "Mexico"},
    {"name":"sushi",
     "first letter":"s",
     "ingredients": ["rice","nori","seaweed", "fish", "tuna", "salmon", "shrimp", "wasabi"],
     "temperature": "room temperature",
      "origin": "Japan"}, 
    {"name":"hamburger",
     "first letter":"h",
     "ingredients": ["bun","hamburger","lettuce", "cheese", "tomato", "onion", "pickles"],
     "temperature": "hot",
      "origin": "USA"}
    ]
